POST http://localhost:8080/api/trains
Content-Type: application/json

{
  "id": 1,
  "login": "admin1",
  "password": "admin1"
}

###

POST http://localhost:8080/api/training
Content-Type: application/json

{
  "trainingTopic": "Chest",
  "date": "11.11.2022 19:00",
  "userId": 1
}

